In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
df = pd.read_csv('NCD_RisC_Nature_2020_Cholesterol_age_specific_countries.csv').reset_index(drop = True)
#df

In [65]:
df.columns

Index(['Country', 'Year', 'Sex', 'Age group',
       'Mean total cholesterol (mmol/L)',
       'Mean total cholesterol lower 95% uncertainty interval (mmol/L)',
       'Mean total cholesterol upper 95% uncertainty interval (mmol/L)',
       'Mean non-HDL cholesterol (mmol/L)',
       'Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)',
       'Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)',
       'Mean HDL cholesterol (mmol/L)',
       'Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)',
       'Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)'],
      dtype='object')

In [66]:
df.rename(columns = {'Sex' : 'Gender',
                     'Age group' : 'Age_group',
                     'Mean total cholesterol (mmol/L)' : 'Mean_total_cholesterol_mmolL',
                     'Mean total cholesterol lower 95% uncertainty interval (mmol/L)' :
                     'Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
                     'Mean total cholesterol upper 95% uncertainty interval (mmol/L)' :
                     'Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
                     'Mean non-HDL cholesterol (mmol/L)' : 'Mean_non_HDL_cholesterol_mmolL',
                     'Mean non-HDL cholesterol lower 95% uncertainty interval (mmol/L)' :
                     'Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
                     'Mean non-HDL cholesterol upper 95% uncertainty interval (mmol/L)' :
                     'Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
                     'Mean HDL cholesterol (mmol/L)' : 'Mean_HDL_cholesterol_mmolL',
                     'Mean HDL cholesterol lower 95% uncertainty interval (mmol/L)' :
                     'Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
                     'Mean HDL cholesterol upper 95% uncertainty interval (mmol/L)' :
                     'Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL'}, inplace = True)

In [67]:
df.columns

Index(['Country', 'Year', 'Gender', 'Age_group',
       'Mean_total_cholesterol_mmolL',
       'Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_mmolL',
       'Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_mmolL',
       'Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL'],
      dtype='object')

In [68]:
df

,Country,Year,Gender,Age_group,Mean_total_cholesterol_mmolL,Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL,Mean_non_HDL_cholesterol_mmolL,Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL,Mean_HDL_cholesterol_mmolL,Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
0,Afghanistan,1980,Men,18-19,3.938280,3.408243,4.450841,2.390296,1.786243,3.001487,1.203759,0.903827,1.491221
1,Afghanistan,1980,Men,20-24,4.030348,3.461665,4.583069,2.565352,2.025941,3.104508,1.207433,0.912178,1.486294
2,Afghanistan,1980,Men,25-29,4.152129,3.523245,4.771284,2.781679,2.317325,3.244324,1.209319,0.917293,1.482287
3,Afghanistan,1980,Men,30-34,4.257240,3.571934,4.923948,2.955077,2.523206,3.386726,1.209177,0.918113,1.481715
4,Afghanistan,1980,Men,35-39,4.339896,3.612904,5.052363,3.081967,2.652806,3.506228,1.209154,0.917683,1.481755
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233995,Zimbabwe,2018,Women,65-69,4.446930,3.602001,5.318344,3.189870,2.774696,3.605794,1.357039,1.110378,1.598515
233996,Zimbabwe,2018,Women,70-74,4.372726,3.524492,5.258760,3.100383,2.645811,3.550462,1.363841,1.121210,1.604588
233997,Zimbabwe,2018,Women,75-79,4.318492,3.447941,5.235428,3.055181,2.555161,3.552644,1.375915,1.130139,1.623145
233998,Zimbabwe,2018,Women,80-84,4.324823,3.411502,5.281729,3.111651,2.550614,3.680846,1.397937,1.141691,1.658576
233999,Zimbabwe,2018,Women,85plus,4.486063,3.426113,5.574371,3.423853,2.672467,4.172845,1.448101,1.148511,1.752269

In [69]:
df.to_csv('NCD_RisC_Nature_2020_Cholesterol_age_specific_countries_sql.csv', index=False, header=True)

In [70]:
df1 = pd.read_csv('NCD_RisC_Nature_2020_Cholesterol_age_specific_countries_sql.csv').reset_index(drop = True)
df1

,Country,Year,Gender,Age_group,Mean_total_cholesterol_mmolL,Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL,Mean_non_HDL_cholesterol_mmolL,Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL,Mean_HDL_cholesterol_mmolL,Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL,Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL
0,Afghanistan,1980,Men,18-19,3.938280,3.408243,4.450841,2.390296,1.786243,3.001487,1.203759,0.903827,1.491221
1,Afghanistan,1980,Men,20-24,4.030348,3.461665,4.583069,2.565352,2.025941,3.104508,1.207433,0.912178,1.486294
2,Afghanistan,1980,Men,25-29,4.152129,3.523245,4.771284,2.781679,2.317325,3.244324,1.209319,0.917293,1.482287
3,Afghanistan,1980,Men,30-34,4.257240,3.571934,4.923948,2.955077,2.523206,3.386726,1.209177,0.918113,1.481715
4,Afghanistan,1980,Men,35-39,4.339896,3.612904,5.052363,3.081967,2.652806,3.506228,1.209154,0.917683,1.481755
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233995,Zimbabwe,2018,Women,65-69,4.446930,3.602001,5.318344,3.189870,2.774696,3.605794,1.357039,1.110378,1.598515
233996,Zimbabwe,2018,Women,70-74,4.372726,3.524492,5.258760,3.100383,2.645811,3.550462,1.363841,1.121210,1.604588
233997,Zimbabwe,2018,Women,75-79,4.318492,3.447941,5.235428,3.055181,2.555161,3.552644,1.375915,1.130139,1.623145
233998,Zimbabwe,2018,Women,80-84,4.324823,3.411502,5.281729,3.111651,2.550614,3.680846,1.397937,1.141691,1.658576
233999,Zimbabwe,2018,Women,85plus,4.486063,3.426113,5.574371,3.423853,2.672467,4.172845,1.448101,1.148511,1.752269

In [71]:
df1.columns

Index(['Country', 'Year', 'Gender', 'Age_group',
       'Mean_total_cholesterol_mmolL',
       'Mean_total_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_total_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_mmolL',
       'Mean_non_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_non_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_mmolL',
       'Mean_HDL_cholesterol_lower_95_percent_uncertainty_interval_mmolL',
       'Mean_HDL_cholesterol_upper_95_percent_uncertainty_interval_mmolL'],
      dtype='object')